### ISSUE TITLE
Error: Debug Failure. False expression:

### ISSUE THREAD

**Issue by pelotom** [danvk/typings-checker#26]
Hey, your library looks really cool and useful! However when I try to run it on any source file of [my library](https://github.com/pelotom/runtypes) it fails with the following error:

```
 ~/code/runtypes » typings-checker --project tsconfig.json src/index.ts
/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:64363
                throw e;
                ^

Error: Debug Failure. False expression:
    at Object.assert (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:3259:23)
    at checkElementTypeOfArrayOrString (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:41263:22)
    at checkIteratedTypeOrElementType (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:41107:24)
    at checkRightHandSideOfForOf (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:41097:20)
    at getTypeForVariableLikeDeclaration (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:27680:24)
    at getWidenedTypeForVariableLikeDeclaration (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:27851:24)
    at getTypeOfVariableOrParameterOrProperty (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:27913:28)
    at checkVariableLikeDeclaration (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:40875:41)
    at checkVariableDeclaration (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:40931:20)
    at checkForInOrForOfVariableDeclaration (/Users/tom/code/runtypes/node_modules/typescript/lib/typescript.js:41092:17)
```

Any ideas?

**Comment by danvk** [comment]
Is that the full stack trace? It's all in typescript library code. Would be helpful if we could see where in `typings-checker` the error is happening.

**Comment by pelotom** [comment]
Yeah, unfortunately that's all that gets printed out :/

**Comment by danvk** [comment]
Try this: http://stackoverflow.com/questions/7697038/more-than-10-lines-in-a-node-js-stack-error

**Comment by pelotom** [comment]
Ah, good trick to know about. I've updated the stack trace.

**Comment by danvk** [comment]
Are you able to run `tsc` on your program?

I believe this is the assertion that's failing (would be helpful if you could double-check)

```ts
            ts.Debug.assert(languageVersion < 2 /* ES2015 */);
```

The line in typings-checker is:

```ts
var diagnostics = ts.getPreEmitDiagnostics(program);
```

which I think just type checks your program.

**Comment by pelotom** [comment]
Yes, `tsc` works fine.

**Comment by danvk** [comment]
I'm able to reproduce your problem, but I'm at a loss as to what it means. You might check out https://github.com/Microsoft/dtslint. Its type linter is based on typings-checker, but it's being more actively developed.

**Comment by amir-arad** [comment]
His all.
This looks like a typescript bug. sometimes typescript crashes on stuff it doesnt expect. in the current typescript version (2.4.2) you can get it when you use this expession for example: 
```ts
function foo<G extends []>(){}
```
the `extends []` crashes Typescript. it used to be a lot worse, they're getting much better at this.
